name = "robo_bdc"
description = "Robo-BDC: Brushed DC Motors Controller"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "robotics"]

project-files = ["gnat/robo_bdc.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
light_blackpill_stm32f401 = "*"
a0b_stm32f401_usart = "*"

[[pins]]
a0b_spi = { path='../a0b-spi' }
a0b_stm32f401_dma = { path='../a0b-stm32f401-dma' }
a0b_stm32f401_gpio = { path='../a0b-stm32f401-gpio' }
a0b_stm32f401_usart = { path='../a0b-stm32f401-usart' }
light_blackpill_stm32f401 = { path='../light-startup/blackpill_stm32f401' }
