# SPDX-FileCopyrightText: 2025 Vadim Godunko <vgodunko@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Build with Alire

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: robo-bdc
    - uses: actions/checkout@v4
      with:
        repository: godunko/a0b-spi
        path: a0b-spi
    - uses: actions/checkout@v4
      with:
        repository: godunko/a0b-stm32f401-gpio
        path: a0b-stm32f401-gpio
    - uses: actions/checkout@v4
      with:
        repository: godunko/a0b-stm32f401-usart
        path: a0b-stm32f401-usart
    - uses: actions/checkout@v4
      with:
        repository: godunko/light-startup
        path: light-startup
    - uses: alire-project/setup-alire@v3
    - name: Build project
      run: alr -C robo-bdc build
